### ISSUE TITLE
MD5 计算错误

### ISSUE THREAD

**Issue by lqzhgood** [ZhangJun2017/QQChatHistoryExporter#1]
如果 MD5 计算出来首位是 0 将被截掉
应该是 这一行 `BigInteger` 导致的 https://github.com/ZhangJun2017/QQChatHistoryExporter/blob/f97eb64581229a30514d55aa0a8423b138b09437/src/Main.java#L34

**Comment by ZhangJun2017** [comment]
感谢，已修复，自己用的时候刚好没碰到这种情况..
