### ISSUE TITLE
Picture CRC64 FileName question

### ISSUE THREAD

**Issue by lqzhgood** [ZhangJun2017/QQChatHistoryExporter#2]
https://github.com/ZhangJun2017/QQChatHistoryExporter/blob/a7bdfc98390a43ee31a3279c7939dc4de827cda5/src/Picture.java#L21-L22

抱歉我对 `Java` 并不擅长 
按我的理解 CRC64.crc64Long 返回的是 二进制字节码数组 <br/>
问下`CRC` 出来的 二进制字节码数组通过 `UTF-8`编码后去掉 **非首位** `-` 后，再通过 `UTF-8` 解码成 二进制字节码数组，再编码成 `HEX` 字符串的特殊处理是为什么呢？  <br/>

另外我在 `https://github.com/Yiyiyimu/QQ-History-Backup` 没有看到额外处理，是直接 CRC -> buffer -> Hex String
https://github.com/Yiyiyimu/QQ-History-Backup/blob/5a82dc1ebeee224aee757e7cf142c414809e8d44/QQ_History.py#L249

**Comment by lqzhgood** [comment]
我知道了，如果 CRC64Value 是 有符号的浮点数，去掉 符号位 "-" 后再转换成 Hex 字符串，最后再拼接上 "-" 。

##### 补充一个 bug
这里的 `CRC64Value` 因为删除符号位的缘故，可能长度会变成单数，需要前面补 0 才能正确转换成 HEX字符串

但是我遍历了 `chatpic\chatimg` 目录，计算了所有 `Cache_` 文件的 MD5 与 文件名进行比较，还是有很多对不上的，这里面还有 bug 。

**Comment by lqzhgood** [comment]
> 我知道了，如果 CRC64Value 是 有符号的浮点数，去掉 符号位 "-" 后再转换成 Hex 字符串，最后再拼接上 "-" 。
> 
> ##### 补充一个 bug
> 这里的 `CRC64Value` 因为删除符号位的缘故，可能长度会变成单数，需要前面补 0 才能正确转换成 HEX字符串
> 
> 但是我遍历了 `chatpic\chatimg` 目录，计算了所有 `Cache_` 文件的 MD5 与 文件名进行比较，还是有很多对不上的，这里面还有 bug 。

应该是不管有没有删除符号位，都有可能是 奇数， 都需要补零。 不然 Str -> Buffer 都会被截断。但还是不能匹配到所有文件

**Comment by lqzhgood** [comment]
搞不定~ 提供一些不符合的样本文件
```
0E5B4FABDCE4BC6C905F3CC78D60AFC3 Cache_6e601cea82f6b013
93C863F244C9F4D54275A87284E9BBB7 Cache_-16f7f7d481994060
23B79CBBB46F5FE977353FEAF86C4034 Cache_3cf044bdb7f9d066
FC25D220A51E90370AE6C5408B1F8002 Cache_-18ab55b22d237070
FB79EC60B2B470B79F1A6BC3B9A74620 Cache_1da079cd154a30af
ADE5051D5BDD28C6368A214411025A72 Cache_51e8d734479f70d9
82F4748A48F589868E41C0DD45ED6864 Cache_431959f8351fa0ed
65B49F2D6D1F2F94128D88193A4E7422 Cache_106c297fd1530144
86777C006107168327E326086FFCFB08 Cache_389d5296c87e8146
8982E90325A808FFDE720EF85E6DFC43 Cache_26440133042a4160
366A3C8CF929D90ECD4289B157676FF8 Cache_-69f87a69bbb891b1
6B830D7570BDF0F6F8C501580C6FE1DC Cache_530be2a58d870215
389C1034ADE23E24EED90C03F263F2FB Cache_210a991bf22d8252
4B5ABA999FE186E66693EC4DE31D6F05 Cache_-e987c115e22826c
8A19DD896270547B08D9AC5459E626AB Cache_3b954e53e2d3a27a
2C14DDBB2D3A70DE10AEB49DF605AE36 Cache_-a385144a8ee02d9
40593C7606B44F78C9CCFC6434532E82 Cache_177fd9e0e97112ed
276F44515EE88353BEDBA8FB8FF6FE3A Cache_-2980ca1f7619d2f2
2DEE7A75D4B221C11553CF647BA8EA6D Cache_455870f4d8c1c38a
D574F786384DE2154F8CE59E0C720A7B Cache_-19f90e7431fe03b1
C2A8384B4EE9FDC069ECE76EA2CA3FCD Cache_-26493fa233adb3be
EF061E3B945EFA16910E019A1968D085 Cache_76322b43a1a5d3c3
4249429F7FBD9B72E4F755D6B642DB84 Cache_96c1c33a3a913e4
DD0AA81F13F37DB0971D01B907D8F40F Cache_-6a988bb313b8c3ea
440C596FA763C4A8BDDBB30B9DE50ED9 Cache_-5ba5b62944433eb
706AF84C2D4F834D8743E2DF71B9C5D5 Cache_-254ba0a1c908c3fd
01ADD7A6429C5D731E68E006F678BA73 Cache_-7b4ca6621ba25421
64CED9F51B5464EF998FB537115F86D8 Cache_-50c613bd6f057526
7851C96C362046B01460A3F2E10332C9 Cache_2599ed7e4ec2e547
C523B42519FED02180A8B80C6B0AAC85 Cache_-76d8c3ea874564
23984DA655FC689306B6DE3878014F45 Cache_681d7ed0d99c9585
B9BBEAA9F8A6E8CC4469078A7F764B3C Cache_-4899c24a807e59f
88F4494EDC90CAFB28C6FEF1A1CCC531 Cache_-4a71f113655da602
501786E355F6E4640559F5DB9417ABC5 Cache_508525b43be3260a
F0C3C27EF81D007D1F18FC9D907B5425 Cache_3879e1968d73642
B0B69D82C90FAF156ABDDF1922751E4E Cache_7857aa1c6037666d
5F4393A65E4FB132EDF3D3F28C327A98 Cache_-6a411bfaffe5f6b9
89472B0AECE2B3C9347DFBE6CE225309 Cache_504324cd3de516be
```

**Comment by ZhangJun2017** [comment]
我对Java也不是很擅长....据文档的说法， `Long.toHexString` 方法在遇到负数参数时的返回值会加上 2^64，大概是为了转换成无符号数？比如`-17`，期望的结果是`-11`但返回值实际是`ffffffffffffffef`。这样手动拼接符号是为了让它与Python中 `hex()` 函数具有同样行为，偷懒写出来的....不过使用上暂时没发现问题。

**Comment by ZhangJun2017** [comment]
另外把样本里的md5用
https://github.com/Yiyiyimu/QQ-History-Backup/blob/5a82dc1ebeee224aee757e7cf142c414809e8d44/QQ_History.py#L16
和
https://github.com/ZhangJun2017/QQChatHistoryExporter/blob/a7bdfc98390a43ee31a3279c7939dc4de827cda5/src/Picture.java#L89
两个方法分别计算发现，在未转换为Hex字符串时部分结果已经不一样了，看来是计算CRC64的方法有问题不过也搞不明白为什么，网上也抄不到其它算出来结果一样的代码（捂脸

**Comment by ZhangJun2017** [comment]
另外md5对不上是因为，如果发图的时候有勾原图的话，QQ会用原图的md5去计算文件名，而原图（包括下载的和本机发出去的）会放在和 `chatimg` 同级的 `chatraw` 目录下，所以部分有原图的图片直接用 `chatimg` 里文件的md5算，自然就对不上了。可以试试用 `chatraw:` 和 `chatimg:` 分别加上原图的md5值，再在对应到目录下寻找文件，代码的话要暑假才有空改了....

**Comment by ZhangJun2017** [comment]
> 另外把样本里的md5用 https://github.com/Yiyiyimu/QQ-History-Backup/blob/5a82dc1ebeee224aee757e7cf142c414809e8d44/QQ_History.py#L16 和
> 
> https://github.com/ZhangJun2017/QQChatHistoryExporter/blob/a7bdfc98390a43ee31a3279c7939dc4de827cda5/src/Picture.java#L89
> 
> 
> 两个方法分别计算发现，在未转换为Hex字符串时部分结果已经不一样了，看来是计算CRC64的方法有问题不过也搞不明白为什么，网上也抄不到其它算出来结果一样的代码（捂脸

&nbsp;
两边算出来不一样的md5是
```
2C14DDBB2D3A70DE10AEB49DF605AE36
D574F786384DE2154F8CE59E0C720A7B
440C596FA763C4A8BDDBB30B9DE50ED9
F0C3C27EF81D007D1F18FC9D907B5425
```

**Comment by lqzhgood** [comment]
> 另外md5对不上是因为，如果发图的时候有勾原图的话，QQ会用原图的md5去计算文件名，而原图（包括下载的和本机发出去的）会放在和 `chatimg` 同级的 `chatraw` 目录下，所以部分有原图的图片直接用 `chatimg` 里文件的md5算，自然就对不上了。可以试试用 `chatraw:` 和 `chatimg:` 分别加上原图的md5值，再在对应到目录下寻找文件，代码的话要暑假才有空改了....

我是逆推的<br/>
从 `chatpic\chatimg` 读取所有文件的 `MD5` ，然后拿这个 `MD5` 和文件名中的 `crc` 值比较，所以应该不存在 `chatimg:` 的问题<br/>
我也尝试了前缀改为 `crc("chatimg:${md5}") == MD5 || crc("chatraw:${md5}") == MD5`  的方式去比较 ，得到不匹配的样本数量是一致的。

**Comment by ZhangJun2017** [comment]
> > 另外md5对不上是因为，如果发图的时候有勾原图的话，QQ会用原图的md5去计算文件名，而原图（包括下载的和本机发出去的）会放在和 `chatimg` 同级的 `chatraw` 目录下，所以部分有原图的图片直接用 `chatimg` 里文件的md5算，自然就对不上了。可以试试用 `chatraw:` 和 `chatimg:` 分别加上原图的md5值，再在对应到目录下寻找文件，代码的话要暑假才有空改了....
> 
> 我是逆推的 从 `chatpic\chatimg` 读取所有文件的 `MD5` ，然后拿这个 `MD5` 和文件名中的 `crc` 值比较，所以应该不存在 `chatimg:` 的问题 我也尝试了前缀改为 `crc("chatimg:${md5}") == MD5 || crc("chatraw:${md5}") == MD5` 的方式去比较 ，得到不匹配的样本数量是一致的。

唔，是说，`chatimg`中存的是压缩过的图片，其中大部分图片文件名中的crc值确实是由文件自身的md5算出来的，但是还有一部分图片，计算文件名时使用的md5来自`chatpic\chatraw`内与之对应的原始画质图片，这部分匹配不上的图片就是发送时勾选了原图发送的图片。

**Comment by lqzhgood** [comment]
哦，懂了
那 `chatraw`中的文件应该就是双向 100% 匹配的了。
但是我 `chatraw`这里面的样本文件太少了，无法足够的进行逆推验证了。


总结一下就是下面这个意思咯？
```
    // F_MD5 代表文件本身的 MD5
    // FN_CRC 代表文件名中的 CRC
    // MSG_MD5 代表数据库中的 MD5

    // chatraw 原图  R_F_MD5 R_FN_CRC
    // chatimg 发送图 I_F_MD5 I_FN_CRC
    // chatthumb 缩略图 T_F_MD5 T_FN_CRC

    // 如果勾选原图
    // chatraw MSG_MD5 == R_F_MD5  CRC(MSG_MD5) == R_FN_CRC  <--原图
    // chatimg MSG_MD5 != I_F_MD5  CRC(MSG_MD5) == I_FN_CRC  <--原图压缩图
    // chatthumb  MSG_MD5 != T_F_MD5 CRC(MSG_MD5) == T_FN_CRC

    // 如果不勾选原图
    // chatraw -无文件
    // chatimg MSG_MD5 == I_F_MD5  CRC(MSG_MD5) == I_FN_CRC  <--原图
    // chatthumb  MSG_MD5 != T_F_MD5 CRC(MSG_MD5) == T_FN_CRC
```

那么推测 同一个文件的 
原图文件名 =  CRC(chatraw:R_F_MD5)
发送图文件名 = CRC(chatimg:R_F_MD5)
缩略图文件名 = CRC(chatthumb:R_F_MD5)

**Comment by lqzhgood** [comment]
> 哦，懂了 那 `chatraw`中的文件应该就是双向 100% 匹配的了。 但是我 `chatraw`这里面的样本文件太少了，无法足够的进行逆推验证了。
> 
> 总结一下就是下面这个意思咯？
> 
> ```
>     // F_MD5 代表文件本身的 MD5
>     // FN_CRC 代表文件名中的 CRC
>     // MSG_MD5 代表数据库中的 MD5
> 
>     // chatraw 原图  R_F_MD5 R_FN_CRC
>     // chatimg 发送图 I_F_MD5 I_FN_CRC
>     // chatthumb 缩略图 T_F_MD5 T_FN_CRC
> 
>     // 如果勾选原图
>     // chatraw MSG_MD5 == R_F_MD5  CRC(MSG_MD5) == R_FN_CRC  <--原图
>     // chatimg MSG_MD5 != I_F_MD5  CRC(MSG_MD5) == I_FN_CRC  <--原图压缩图
>     // chatthumb  MSG_MD5 != T_F_MD5 CRC(MSG_MD5) == T_FN_CRC
> 
>     // 如果不勾选原图
>     // chatraw -无文件
>     // chatimg MSG_MD5 == I_F_MD5  CRC(MSG_MD5) == I_FN_CRC  <--原图
>     // chatthumb  MSG_MD5 != T_F_MD5 CRC(MSG_MD5) == T_FN_CRC
> ```
> 
> 那么推测 同一个文件的 原图文件名 = CRC(chatraw:R_F_MD5) 发送图文件名 = CRC(chatimg:R_F_MD5) 缩略图文件名 = CRC(chatthumb:R_F_MD5)

验证了一下上面的推测

```js
const rawArr = rawFileMd5Arr.map(md5=>{
    return  {
            raw: imageCrc64(`chatraw:${md5.toUpperCase()}`),
            img: imageCrc64(`chatimg:${md5.toUpperCase()}`),
            thu: imageCrc64(`chatthumb:${md5.toUpperCase()}`),
        }
})


for (let i = 0; i < rawArr.length; i++) {
    const o = rawArr[i];
    const find = imgFileNameArr.find(v => v.includes(o.img));
    const find2 = thuFileNameArr.find(v => v.includes(o.thu));

    if (find) {
        // 没有匹配到任何数据
    }

    if (find2) {
        // 匹配到了文件 且图片内容一致 大小不一致
    }

    if (find && find2) {
        // 没有匹配到任何数据
    }
}
```
`chatthumb ` 通过验证， `chatimg` 没匹配到 不排除 CRC64 方法有问题

CRC64 方法我通过 shell 调用的 Python， https://github.com/Yiyiyimu/QQ-History-Backup/blob/5a82dc1ebeee224aee757e7cf142c414809e8d44/QQ_History.py#L16 并进行了奇数 **首位** 补零

**Comment by ZhangJun2017** [comment]
`chatthumb`通过了验证，大概 CRC64 方法没有问题。`chatimg`匹配不到可能是因为很少点查看原图，`chatraw`目录下存的都是自己发出去的原图，发送的原图不会压缩后再存一份到`chatimg`里。

**Comment by lqzhgood** [comment]
解决奇数  **首位** 补零的 bug，应该就没问题了
