### ISSUE TITLE
proto 是怎么解密的能简单说下么？

### ISSUE THREAD

**Issue by lqzhgood** [ZhangJun2017/QQChatHistoryExporter#3]
https://github.com/ZhangJun2017/QQChatHistoryExporter/blob/a7bdfc98390a43ee31a3279c7939dc4de827cda5/src/RichMsgHandle.proto#L100-L107

例如 `Tip` , 后面的这个 5 9 8 的值是怎么来呢?
<hr/>

```
['48,55,34,53,28,42,213,156,138,212,175,136,212,167,149,221,173,172,209,140,183,212,139,179,212,164,144,212,131,185,222,183,157,117,54']
``` 
是怎么逆向编码成 
``` 
{"tip":"对方撤回了一条消息"}
``` 

我看了下网上的 `protobuf` 的教程也毫无头绪，能简单说说 `protobuf` 逆向的思路么？

**Comment by ZhangJun2017** [comment]
获取用密钥解密后的数据可以参考
https://github.com/Yiyiyimu/QQ-History-Backup/blob/b7d9726ecf7f029e770ae5f62f1c36541f463714/QQ_History.py#L56-L58
或
https://github.com/ZhangJun2017/QQChatHistoryExporter/blob/a7bdfc98390a43ee31a3279c7939dc4de827cda5/src/RawMessage.java#L109-L120
&nbsp;
可以写出到文件然后使用`protobuf`编译器提供的`protoc --decode_raw < 文件路径`，或者用[这个网站](https://protobuf-decoder.netlify.app/)，更直观一点。找到想要的数据后根据序号编写对应的`proto`文件并使用编译器生成对应语言的代码即可，参考[这篇文章](https://www.jianshu.com/p/1aeb8ee87b99)。
&nbsp;

> `['48,55,34,53,28,42,213,156,138,212,175,136,212,167,149,221,173,172,209,140,183,212,139,179,212,164,144,212,131,185,222,183,157,117,54']`

这个没明白是什么....
&nbsp;
附一份解密好了的数据
`08 01 10 20 2a 1b e5 af b9 e6 96 b9 e6 92 a4 e5 9b 9e e4 ba 86 e4 b8 80 e6 9d a1 e6 b6 88 e6 81 af 40 20 4a 08 08 20 10 20 30 20 38 20 `
